debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.study.trainingboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  profiles:
    active:
      - local-db
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    hibernate.ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    open-in-view: ${spring.jpa.open-in-view}
    show-sql: ${spring.jpa.show-sql}
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    defer-datasource-initialization: true
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  h2.console.enabled: true
  thymeleaf3:
    decoupled-logic: true



